package view;

import dao.AccountDao;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.time.Year;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Account;
import service.AccountServices;

public class XemVaCapNhatTK309 extends javax.swing.JFrame {

    private Account acc309;
    private String maThe309;
    private String fileName309;
    private AccountServices accServices309;

    public XemVaCapNhatTK309(String maThe) throws SQLException {
        this.maThe309 = maThe;
        accServices309 = new AccountServices();
        acc309 = accServices309.getAccountByMaThe309(maThe);
        fileName309 = null;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        initComboBox309();
        setDataUpdateFrame();
        ImageIcon icon = new ImageIcon(new ImageIcon("src\\Icons\\LogoVietinBank2.png").getImage().getScaledInstance(logoLabel309.getWidth(), logoLabel309.getHeight(), Image.SCALE_SMOOTH));
        logoLabel309.setIcon(icon);
    }

    XemVaCapNhatTK309() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(new ImageIcon("src\\Icons\\LogoVietinBank2.png").getImage().getScaledInstance(logoLabel309.getWidth(), logoLabel309.getHeight(), Image.SCALE_SMOOTH));
        logoLabel309.setIcon(icon);
    }

    // Khởi tạo dữ liệu ngày/tháng/năm cho các comboBox tương ứng
    public void initComboBox309() {
        // yearComboBox
        Vector yearData309 = new Vector();
        int year = Year.now().getValue();
        for (int i = year; i >= 1900; i--) {
            yearData309.add("" + i);
        }
        DefaultComboBoxModel yearDCBM = new DefaultComboBoxModel(yearData309);
        yearComboBox309.setModel(yearDCBM);

        // monthComboBox
        Vector monthData309 = new Vector();
        for (int i = 1; i <= 12; i++) {
            if (i > 9) {
                monthData309.add("" + i);
            } else {
                monthData309.add("0" + i);
            }
        }
        DefaultComboBoxModel monthDCBM = new DefaultComboBoxModel(monthData309);
        monthComboBox309.setModel(monthDCBM);

        // dayComboBox
        Vector dayData309 = new Vector();
        for (int i = 1; i <= 31; i++) {
            if (i > 9) {
                dayData309.add("" + i);
            } else {
                dayData309.add("0" + i);
            }
        }
        DefaultComboBoxModel dayDCBM = new DefaultComboBoxModel(dayData309);
        dayComboBox309.setModel(dayDCBM);
    }

    // Gán dữ liệu acc309 vào updateFrame bằng MaThe
    public void setDataUpdateFrame() throws SQLException {
        byte[] image = acc309.getAnh();
        if (image != null) {
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(imageLabel309.getWidth(), imageLabel309.getHeight(), Image.SCALE_SMOOTH));
            imageLabel309.setIcon(imageIcon);
            imageLabel309.setText("");
        }
        maTheTextField309.setText(acc309.getMaThe());
        userNameTextField309.setText(acc309.getTenDangNhap());
        nameTextField309.setText(acc309.getHoTen());
        dayComboBox309.setSelectedItem(acc309.getNgaySinh().substring(8));
        monthComboBox309.setSelectedItem(acc309.getNgaySinh().substring(5, 7));
        yearComboBox309.setSelectedItem(acc309.getNgaySinh().substring(0, 4));
        phoneNumberTextField309.setText(acc309.getSdt());
        emailTextField309.setText(acc309.getEmail());
        addressTextField309.setText(acc309.getDiaChi());
        cmndTextField309.setText(acc309.getCmnd());
        PasswordField309.setText(acc309.getMaKhau());

        if (acc309.getGioiTinh().equals("Nam")) {
            maleRadioButton309.setSelected(true);
        } else if (acc309.getGioiTinh().equals("Nữ")) {
            femaleRadioButton309.setSelected(true);
        } else {
            gayRadioButton309.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        genderButtonGroup = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emailTextField309 = new javax.swing.JTextField();
        addressTextField309 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        phoneNumberTextField309 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        imageLabel309 = new javax.swing.JLabel();
        deleteImageButton309 = new javax.swing.JButton();
        chooseImageButton309 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmndTextField309 = new javax.swing.JTextField();
        nameTextField309 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        maleRadioButton309 = new javax.swing.JRadioButton();
        femaleRadioButton309 = new javax.swing.JRadioButton();
        gayRadioButton309 = new javax.swing.JRadioButton();
        dayComboBox309 = new javax.swing.JComboBox<>();
        yearComboBox309 = new javax.swing.JComboBox<>();
        monthComboBox309 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userNameTextField309 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PasswordField309 = new javax.swing.JPasswordField();
        maTheTextField309 = new javax.swing.JTextField();
        visiblePasswordButton309 = new javax.swing.JToggleButton();
        backButton309 = new javax.swing.JButton();
        updateButton309 = new javax.swing.JButton();
        logoLabel309 = new javax.swing.JLabel();

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_back_16px.png"))); // NOI18N
        jButton2.setText("Trở về");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xem và cập nhật thông tin");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HỒ SƠ");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("E-mail");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("SĐT");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Địa chỉ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Thông tin liên lạc");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailTextField309, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addressTextField309, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phoneNumberTextField309)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(phoneNumberTextField309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(emailTextField309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        imageLabel309.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        imageLabel309.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel309.setText("Ảnh");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel309, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel309, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        deleteImageButton309.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Delete_16px.png"))); // NOI18N
        deleteImageButton309.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteImageButton309ActionPerformed(evt);
            }
        });

        chooseImageButton309.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_upload_16px_4.png"))); // NOI18N
        chooseImageButton309.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImageButton309ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Giới tính");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("CMND/CCCD");

        nameTextField309.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextField309ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Ngày sinh");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Thông tin cá nhân");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Họ tên");

        maleRadioButton309.setBackground(new java.awt.Color(153, 204, 255));
        genderButtonGroup.add(maleRadioButton309);
        maleRadioButton309.setSelected(true);
        maleRadioButton309.setText("Nam");
        maleRadioButton309.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButton309ActionPerformed(evt);
            }
        });

        femaleRadioButton309.setBackground(new java.awt.Color(153, 204, 255));
        genderButtonGroup.add(femaleRadioButton309);
        femaleRadioButton309.setText("Nữ");

        gayRadioButton309.setBackground(new java.awt.Color(153, 204, 255));
        genderButtonGroup.add(gayRadioButton309);
        gayRadioButton309.setText("Khác");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField309)
                            .addComponent(cmndTextField309)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maleRadioButton309, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dayComboBox309, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(femaleRadioButton309, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(8, 8, 8)
                                        .addComponent(gayRadioButton309, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(20, 20, 20))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(monthComboBox309, 0, 54, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yearComboBox309, 0, 75, Short.MAX_VALUE))))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nameTextField309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmndTextField309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dayComboBox309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearComboBox309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthComboBox309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(maleRadioButton309, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gayRadioButton309, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(femaleRadioButton309, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(chooseImageButton309, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(deleteImageButton309))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteImageButton309, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chooseImageButton309, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mật khẩu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tên đăng nhập");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Mã thẻ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Thông tin tài khoản");

        PasswordField309.setBackground(new java.awt.Color(240, 240, 240));
        PasswordField309.setEnabled(false);
        PasswordField309.setPreferredSize(new java.awt.Dimension(97, 25));

        maTheTextField309.setEnabled(false);

        visiblePasswordButton309.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_invisible_16px_2.png"))); // NOI18N
        visiblePasswordButton309.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visiblePasswordButton309ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(userNameTextField309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maTheTextField309)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(PasswordField309, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(visiblePasswordButton309))))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(maTheTextField309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userNameTextField309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordField309, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(visiblePasswordButton309, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backButton309.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_back_16px.png"))); // NOI18N
        backButton309.setText("Trở về");
        backButton309.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton309ActionPerformed(evt);
            }
        });

        updateButton309.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_update_16px.png"))); // NOI18N
        updateButton309.setText("Cập nhập");
        updateButton309.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton309ActionPerformed(evt);
            }
        });

        logoLabel309.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(backButton309)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton309))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(logoLabel309, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(logoLabel309, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton309)
                    .addComponent(backButton309))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleRadioButton309ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButton309ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioButton309ActionPerformed

    private void chooseImageButton309ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImageButton309ActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Hình ảnh", "jpg", "png"); // lọc loại file
        filechooser.setFileFilter(imageFilter);
        filechooser.setMultiSelectionEnabled(false); // không cho phép chọn nhiều dòng
        int x = filechooser.showDialog(this, "Chọn file");
        if (x == JFileChooser.APPROVE_OPTION) { // đã chọn file
            File f = filechooser.getSelectedFile();
            fileName309 = f.getAbsolutePath();
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName309).getImage().getScaledInstance(imageLabel309.getWidth(), imageLabel309.getHeight(), Image.SCALE_SMOOTH));
            imageLabel309.setIcon(imageIcon);
            imageLabel309.setText("");

            // Chuyển từ ảnh sang mảng byte và lưu lại
            try {
                File image = new File(fileName309);
                FileInputStream fis = new FileInputStream(image); // đọc file dưới dạng chuỗi byte
                ByteArrayOutputStream baos = new ByteArrayOutputStream(); // ByteArrayOutputStream được sử dụng để ghi các bytes vào 1 mảng byte
                byte[] bytes = new byte[1024];
                for (int readNum; (readNum = fis.read(bytes)) != -1;) { //Đọc toàn bộ nội dung file
                    baos.write(bytes, 0, readNum); 
                }
                acc309.setAnh(baos.toByteArray());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(XemVaCapNhatTK309.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(XemVaCapNhatTK309.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_chooseImageButton309ActionPerformed

    private void deleteImageButton309ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteImageButton309ActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn gỡ ảnh không?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        imageLabel309.setIcon(null);
        imageLabel309.setText("Ảnh");
        acc309.setAnh(null);
    }//GEN-LAST:event_deleteImageButton309ActionPerformed

    private void updateButton309ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton309ActionPerformed
        // TODO add your handling code here:
        //XỬ LÝ LỖI NHẬP DỮ LIỆU
        if (nameTextField309.getText().equals("")) {// họ tên
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập họ tên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            nameTextField309.requestFocus();
            return;
        }
        if (cmndTextField309.getText().equals("")) { //CMND/CCCD
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập CMND/CCCD!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            cmndTextField309.requestFocus();
            return;
        }

        try { // CMND/CCCD không phải số nguyên thì in ra lỗi.
            Long.parseLong(cmndTextField309.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chỉ nhập được nhập số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            cmndTextField309.requestFocus();
            return;
        }
        
        if(cmndTextField309.getText().length() != 12 && cmndTextField309.getText().length() != 9) { // kiểm tra độ dài cmnd/cccd
            JOptionPane.showMessageDialog(this, "Nhập thừa hoặc thiếu số CMND/CCCD!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            cmndTextField309.requestFocus();
            return;
        }
        if (phoneNumberTextField309.getText().equals("")) {// SĐT
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập SĐT!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            phoneNumberTextField309.requestFocus();
            return;
        }
        
        try { // SĐT không phải số nguyên thì in ra lỗi.
            Long.parseLong(phoneNumberTextField309.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chỉ nhập số!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            phoneNumberTextField309.requestFocus();
            return;
        }
        
        if(phoneNumberTextField309.getText().length() != 10 && phoneNumberTextField309.getText().length() != 11) { // kiểm tra độ dài sđt
            JOptionPane.showMessageDialog(this, "Nhập thừa hoặc thiếu số SĐT!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            phoneNumberTextField309.requestFocus();
            return;
        }
        if (emailTextField309.getText().equals("")) { // email
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Email!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            emailTextField309.requestFocus();
            return;
        }
        
        // kiểm tra gmail
        String regex = "^(.+)@gmail.com"; //chuỗi đứng trước ký tự @ không có ký tự "." "+"
        Pattern pattern = Pattern.compile(regex); 
        Matcher matcher = pattern.matcher(emailTextField309.getText());
        if(!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Nhập sai Email!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            emailTextField309.requestFocus();
            return;
        }
        
        if (addressTextField309.getText().equals("")) { // địa chỉ
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập địa chỉ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            addressTextField309.requestFocus();
            return;
        }
        if (userNameTextField309.getText().equals("")) { // username
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên đăng nhập!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            userNameTextField309.requestFocus();
            return;
        }
        // Kết thúc sử lý lỗi nhập dữ liệu
        
        // Xác nhận
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật không?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        // Lấy dữ liệu từ form và cập nhật
        try {
            acc309.setHoTen(nameTextField309.getText());
            acc309.setCmnd(cmndTextField309.getText());
            acc309.setNgaySinh(monthComboBox309.getSelectedItem() + "/" + dayComboBox309.getSelectedItem() + "/" + yearComboBox309.getSelectedItem());
            if (maleRadioButton309.isSelected()) {
                acc309.setGioiTinh(String.valueOf(maleRadioButton309.getText()));
            }
            if (femaleRadioButton309.isSelected()) {
                acc309.setGioiTinh(String.valueOf(femaleRadioButton309.getText()));
            }
            if (gayRadioButton309.isSelected()) {
                acc309.setGioiTinh(String.valueOf(gayRadioButton309.getText()));
            }

            acc309.setSdt(phoneNumberTextField309.getText());
            acc309.setEmail(emailTextField309.getText());
            acc309.setDiaChi(addressTextField309.getText());
            acc309.setMaThe(maTheTextField309.getText());
            acc309.setTenDangNhap(userNameTextField309.getText());
            acc309.setMaKhau(String.valueOf(PasswordField309.getPassword()));
            if (accServices309.UpdateAccount309(acc309)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(XemVaCapNhatTK309.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButton309ActionPerformed

    private void backButton309ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton309ActionPerformed
        // TODO add your handling code here:
        new menu331().setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_backButton309ActionPerformed

    private void nameTextField309ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextField309ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextField309ActionPerformed

    private void visiblePasswordButton309ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visiblePasswordButton309ActionPerformed
        // TODO add your handling code here:
        if (visiblePasswordButton309.isSelected()) {
            visiblePasswordButton309.setIcon(new ImageIcon("src\\icons\\icons8_eye_16px_1.png"));
            PasswordField309.setEchoChar((char) 0);
        } else {
            visiblePasswordButton309.setIcon(new ImageIcon("src\\icons\\icons8_invisible_16px_2.png"));
            PasswordField309.setEchoChar('*');
        }
    }//GEN-LAST:event_visiblePasswordButton309ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemVaCapNhatTK309.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemVaCapNhatTK309.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemVaCapNhatTK309.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemVaCapNhatTK309.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new XemVaCapNhatTK309().setVisible(true);
                try {
                    new XemVaCapNhatTK309("100000000013").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(XemVaCapNhatTK309.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField309;
    private javax.swing.JTextField addressTextField309;
    private javax.swing.JButton backButton309;
    private javax.swing.JButton chooseImageButton309;
    private javax.swing.JTextField cmndTextField309;
    private javax.swing.JComboBox<String> dayComboBox309;
    private javax.swing.JButton deleteImageButton309;
    private javax.swing.JTextField emailTextField309;
    private javax.swing.JRadioButton femaleRadioButton309;
    private javax.swing.JRadioButton gayRadioButton309;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel imageLabel309;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel logoLabel309;
    private javax.swing.JTextField maTheTextField309;
    private javax.swing.JRadioButton maleRadioButton309;
    private javax.swing.JComboBox<String> monthComboBox309;
    private javax.swing.JTextField nameTextField309;
    private javax.swing.JTextField phoneNumberTextField309;
    private javax.swing.JButton updateButton309;
    private javax.swing.JTextField userNameTextField309;
    private javax.swing.JToggleButton visiblePasswordButton309;
    private javax.swing.JComboBox<String> yearComboBox309;
    // End of variables declaration//GEN-END:variables
}
